title: Abhinav R
describtion: Motivated and detail-oriented recent graduate with
internship experience in data analysis, seeking a data
Analyst position. Strong analytical skills and a proven
ability to collaborate effectively with project stakeholders
show_downlods: True
theme: jekyll-theme-minimal
